### ISSUE TITLE
Model and check point version don't match 

### ISSUE THREAD

**Issue by AnnyShen55** [EternalEvan/FlowIE#10]
Hello I try the demo pictures, but the result shows that sth is unmatched. Below is what i have  
<img width="455" alt="Screenshot 2024-07-08 at 3 54 31 PM" src="https://github.com/EternalEvan/FlowIE/assets/75340752/63a91ee0-d1f1-4b95-8247-2b1630d46dac"> for the picture
<img width="566" alt="Screenshot 2024-07-08 at 3 54 41 PM" src="https://github.com/EternalEvan/FlowIE/assets/75340752/9aab76a8-5ea6-4253-90f2-a886bdfe470f">

this is what i used:
python inference_bfr.py --ckpt ./weights/FlowIE_bfr_v1.ckpt  --input ./assets/faces --output ./outputs/demo

**Comment by NhomNhom0** [comment]
@AnnyShen55 how can you able to resolve that. I have the same issue
