### ISSUE TITLE
No FlowIE_bsr_v1.ckpt found

### ISSUE THREAD

**Issue by zdyshine** [EternalEvan/FlowIE#2]
Great work, I couldn't find the weight FlowIE_bsr_v1.ckpt in [the provided connection](https://cloud.tsinghua.edu.cn/d/4fa2a0880a9243999561/). Will it be open source in the future?

**Comment by EternalEvan** [comment]
Thank you for your interest! The weight FlowIE_bsr_v1.ckpt will be released in the next few weeks.

**Comment by zdyshine** [comment]
> Thank you for your interest! The weight FlowIE_bsr_v1.ckpt will be released in the next few weeks.

感谢回复，我想尝试自己训练，请问stable-diffusion-2-1-base里面所有的文件都需要下载吗，还是只需要下载其中的一个模型就可以了？
https://huggingface.co/stabilityai/stable-diffusion-2-1-base/tree/main

**Comment by GiuseppeFiorillo** [comment]
Hello, did you solve this problem?

**Comment by MuhammadEmmadSiddiqui** [comment]
> Thank you for your interest! The weight FlowIE_bsr_v1.ckpt will be released in the next few weeks.

Hi @EternalEvan, I still cannot find the FlowIE_bsr_v1.ckpt file in the provided link. Can you help me obtain this weights file?
